export const spanishLocalization = {
  pagePrevText: "Anterior",
  pageNextText: "Siguiente",
  completeText: "Guardar",
  previewText: "Vista previa",
  editText: "Editar",
  startSurveyText: "Comenzar",
  otherItemText: "Otro (describir)",
  noneItemText: "Ninguno",
  selectAllItemText: "Seleccionar todo",
  progressText: "Página {0} de {1}",
  indexText: "{0} de {1}",
  panelDynamicProgressText: "{0} de {1}",
  panelDynamicTabTextFormat: "Panel {panelIndex}",
  questionsProgressText: "Respondidas {0}/{1} preguntas",
  emptySurvey: "No hay página visible o pregunta en la encuesta.",
  completingSurvey: "¡Gracias por completar la encuesta!",
  completingSurveyBefore: "Nuestros registros muestran que ya has completado esta encuesta.",
  loadingSurvey: "Cargando encuesta...",
  placeholder: "Seleccionar...",
  ratingOptionsCaption: "Seleccionar...",
  value: "valor",
  requiredError: "Por favor responda la pregunta.",
  requiredErrorInPanel: "Por favor responda al menos una pregunta.",
  requiredInAllRowsError: "Por favor responda las preguntas en todas las filas.",
  numericError: "El valor debe ser numérico.",
  minError: "El valor no debe ser menor que {0}",
  maxError: "El valor no debe ser mayor que {0}",
  textMinLength: "Por favor ingrese al menos {0} caracteres.",
  textMaxLength: "Por favor ingrese menos de {0} caracteres.",
  textMinMaxLength: "Por favor ingrese más de {0} y menos de {1} caracteres.",
  minRowCountError: "Por favor llene al menos {0} filas.",
  minSelectError: "Por favor seleccione al menos {0} variantes.",
  maxSelectError: "Por favor seleccione no más de {0} variantes.",
  numericMinMax: "El '{0}' debe ser igual o mayor que {1} y menor o igual que {2}",
  numericMin: "El '{0}' debe ser igual o mayor que {1}",
  numericMax: "El '{0}' debe ser igual o menor que {1}",
  invalidEmail: "Por favor ingrese un correo electrónico válido.",
  invalidExpression: "La expresión: {0} debe devolver 'verdadero'.",
  urlRequestError: "La solicitud retornó error '{0}'. {1}",
  urlGetChoicesError: "La solicitud retornó datos vacíos o la propiedad 'path' es incorrecta",
  exceedMaxSize: "El tamaño del archivo no debe exceder {0}.",
  otherRequiredError: "Por favor ingrese el valor para su respuesta.",
  uploadingFile: "Su archivo se está cargando. Por favor espere unos segundos e intente nuevamente.",
  loadingFile: "Cargando...",
  chooseFile: "Elija archivo(s)...",
  noFileChosen: "No se ha elegido ningún archivo",
  filePlaceholder: "Arrastre y suelte un archivo aquí o haga clic en el botón de abajo y elija un archivo para cargar.",
  confirmDelete: "¿Desea borrar el registro?",
  keyDuplicationError: "Este valor debe ser único.",
  addColumn: "Agregar columna",
  addRow: "Agregar fila",
  removeRow: "Eliminar",
  emptyRowsText: "No hay filas.",
  addPanel: "Agregar nuevo",
  removePanel: "Eliminar",
  choices_Item: "ítem",
  matrix_column: "Columna",
  matrix_row: "Fila",
  multipletext_itemname: "texto",
  savingData: "Los resultados se están guardando en el servidor...",
  savingDataError: "Se produjo un error y no pudimos guardar los resultados.",
  savingDataSuccess: "¡Los resultados se guardaron con éxito!",
  saveAgainButton: "Intente nuevamente",
  timerMin: "min",
  timerSec: "seg",
  timerSpentAll: "Ha pasado {0} en esta página y {1} en total.",
  timerSpentPage: "Ha pasado {0} en esta página.",
  timerSpentSurvey: "Ha pasado {0} en total.",
  timerLimitAll: "Ha pasado {0} de {1} en esta página y {2} de {3} en total.",
  timerLimitPage: "Ha pasado {0} de {1} en esta página.",
  timerLimitSurvey: "Ha pasado {0} de {1} en total.",
  clearCaption: "Limpiar",
  signaturePlaceHolder: "Firmar aquí",
  chooseFileCaption: "Elegir archivo",
  takePhotoCaption: "Tomar foto",
  photoPlaceholder: "Haga clic en el botón de abajo para tomar una foto usando la cámara.",
  fileOrPhotoPlaceholder: "Arrastre y suelte o seleccione un archivo para cargar o tomar una foto usando la cámara.",
  replaceFileCaption: "Reemplazar archivo",
  removeFileCaption: "Eliminar este archivo",
  booleanCheckedLabel: "Sí",
  booleanUncheckedLabel: "No",
  confirmRemoveFile: "¿Está seguro que desea eliminar este archivo: {0}?",
  confirmRemoveAllFiles: "¿Está seguro que desea eliminar todos los archivos?",
  questionTitlePatternText: "Título de la pregunta",
  modalCancelButtonText: "Cancelar",
  modalApplyButtonText: "Aplicar",
  filterStringPlaceholder: "Escriba para buscar...",
  emptyMessage: "No hay datos para mostrar",
  noEntriesText: "Aún no hay entradas.\nHaga clic en el botón de abajo para agregar una nueva entrada.",
  noEntriesReadonlyText: "No hay entradas.",
  more: "Más",
  tagboxDoneButtonCaption: "OK",
  selectToRankEmptyRankedAreaText: "Todas las opciones están clasificadas",
  selectToRankEmptyUnrankedAreaText: "Arrastre y suelte las opciones aquí para clasificarlas"
}; 